### ISSUE TITLE
has no method 'extend' issue occurring 

### ISSUE THREAD

**Issue by Dineshaws** [rmm5t/jquery-timeago#236]
This issue comes in version 1.4.2. however i had installed 0.2.0  version which was running fine.

following error attached.

  $.extend($.timeago, {
    ^
TypeError: Object function ( w ) {
                                if ( !w.document ) {
                                        throw new Error( "jQuery requires a window with a document" );
                                }
                                return factory( w );
                        } has no method 'extend'
    at /var/www/html/snapak/node_modules/timeago/jquery.timeago.js:41:5
    at $.timeago (/var/www/html/snapak/node_modules/timeago/jquery.timeago.js:22:5)
    at Object.<anonymous> (/var/www/html/snapak/node_modules/timeago/jquery.timeago.js:27:2)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)

suggest a solution. Thanks

**Comment by jpalomar** [comment]
this could be a race condition with jQuery not being established in the window namespace yet.  try including my fix that I've opened in this issue: https://github.com/rmm5t/jquery-timeago/issues/239 and put in this pull request: https://github.com/rmm5t/jquery-timeago/pull/238

**Comment by jpalomar** [comment]
or you can put a requirejs shim in for the timeago file --  'shim' : { 'timeago' : ['jquery'] }

**Comment by rmm5t** [comment]
This should be fixed thanks to #239 by @jpalomar.  Please try v1.4.3.

**Comment by DABH** [comment]
I'm encountering basically the same error with v1.4.3.  I'm including timeago in a node.js controller (server-side) with
var timeago=require('timeago');

When running my node server, I get the error

/home/user/project/node_modules/timeago/jquery.timeago.js:41
  $.extend($.timeago, {
    ^

TypeError: $.extend is not a function
    at /home/user/project/node_modules/timeago/jquery.timeago.js:41:5
    at /home/user/project/node_modules/timeago/jquery.timeago.js:22:5
    at Object.<anonymous> (/home/user/project/node_modules/timeago/jquery.timeago.js:27:2)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
...

I'm using jquery 2.1.4 and timeago 1.4.3 to get this error.  Previously, my code worked with jquery 2.1.3 and timeago 0.2.0.  Any ideas how to debug this / what the problem could be?  Thanks!
